import json
import os
from typing import Any

import httpx


async def generate_report(
    variant: dict[str, Any],
    annotations: dict[str, Any],
    similar_variants: list[dict[str, Any]],
    structures: dict[str, Any],
) -> dict[str, Any]:
    """Generate final report content.

    Contributor task:
    - Use Claude with strict instructions to only use structured evidence.
    - Return markdown plus structured JSON for frontend rendering.
    """
    evidence = _structured_evidence(variant, annotations, similar_variants, structures)
    
    claude_result = await _claude_report(evidence)
    groq_result = await _groq_report(evidence) if not claude_result else None
    ollama_result = await _ollama_report(evidence) if not claude_result and not groq_result else None
    
    ai_markdown = claude_result or groq_result or ollama_result
    
    if claude_result:
        print("[reporter] Report generated by Claude", flush=True)
    elif groq_result:
        print("[reporter] Report generated by Groq", flush=True)
    elif ollama_result:
        print("[reporter] Report generated by Ollama", flush=True)
    else:
        print("[reporter] No LLM succeeded — using fallback markdown", flush=True)

    markdown = ai_markdown or _fallback_markdown(evidence)

    return {
        "markdown": markdown,
        "json": {
            "status": "complete",
            "variant": evidence["variant"],
            "classification_summary": evidence["classification_summary"],
            "wild_type": evidence["wild_type"],
            "unknown_variant": evidence["unknown_variant"],
            "similar_variants": evidence["similar_variants"],
            "structures": evidence["structures"],
            "warnings": evidence["warnings"],
            "disclaimer": (
                "Research support only. This is not medical advice, diagnosis, or treatment guidance."
            ),
        },
    }


def _structured_evidence(
    variant: dict[str, Any],
    annotations: dict[str, Any],
    similar_variants: list[dict[str, Any]],
    structures: dict[str, Any],
) -> dict[str, Any]:
    parsed_variant = annotations.get("variant") or variant
    features = annotations.get("features") or {}
    alpha = annotations.get("alpha_missense") or {}
    clinvar_records = annotations.get("clinvar", {}).get("records") or []
    warnings = []
    warnings.extend(annotations.get("warnings") or [])
    warnings.extend(features.get("warnings") or [])

    return {
        "variant": parsed_variant,
        "classification_summary": {
            "alpha_missense": alpha,
            "clinvar": clinvar_records[:5],
            "gnomad": annotations.get("gnomad"),
            "overall_interpretation": _overall_interpretation(alpha, clinvar_records),
        },
        "wild_type": {
            "gene": parsed_variant.get("gene"),
            "protein": annotations.get("uniprot", {}).get("protein_name"),
            "uniprot": annotations.get("uniprot"),
            "sequence_length": annotations.get("uniprot", {}).get("length"),
            "description": _wild_type_description(annotations),
        },
        "unknown_variant": {
            "display_name": parsed_variant.get("display_name"),
            "mutation": parsed_variant.get("mutation"),
            "features": features,
            "description": _unknown_variant_description(parsed_variant, features),
        },
        "similar_variants": [
            {
                "name": item.get("name"),
                "source": item.get("source"),
                "similarity_score": item.get("similarity_score"),
                "similarity_reasons": item.get("similarity_reasons"),
                "clinical_significance": item.get("clinical_significance"),
                "description": item.get("description"),
            }
            for item in similar_variants
        ],
        "structures": structures,
        "warnings": warnings,
    }


async def _claude_report(evidence: dict[str, Any]) -> str | None:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return None
    try:
        import anthropic

        client = anthropic.AsyncAnthropic(api_key=api_key)
        message = await client.messages.create(
            model=os.getenv("FOLDEX_CLAUDE_MODEL", "claude-3-5-sonnet-latest"),
            max_tokens=1800,
            temperature=0,
            messages=[
                {
                    "role": "user",
                    "content": (
                        "Generate a concise variant research report in markdown using only the "
                        "structured evidence below. Do not invent symptoms, diagnoses, population "
                        "frequencies, pathogenicity, papers, or structures. If evidence is missing, "
                        "say it is missing. Include sections for classification, wild type, unknown "
                        "variant features, similar variants, likely behavior/expression based only on "
                        "similar known variants, 3D structures, and research-only disclaimer.\n\n"
                        f"{json.dumps(evidence, indent=2)}"
                    ),
                }
            ],
        )
        return "".join(block.text for block in message.content if hasattr(block, "text"))
    except Exception as exc:
        print(f"[reporter] Claude failed: {exc}", flush=True)
        return None


async def _groq_report(evidence: dict[str, Any]) -> str | None:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return None

    model = os.getenv("FOLDEX_GROQ_MODEL", "llama-3.3-70b-versatile")
    url = "https://api.groq.com/openai/v1/chat/completions"
    # Strip raw PDB strings before sending to Groq — they are hundreds of KB and
    # will exceed the model's context window, causing a silent 400/413 failure.
    slim = _slim_evidence(evidence)
    prompt = (
        "Generate a concise variant research report in markdown using ONLY the structured "
        "evidence provided below. Do not invent symptoms, diagnoses, population frequencies, "
        "pathogenicity, papers, or structures. If evidence is missing, explicitly say it is missing. "
        "CRITICAL: The similar_variants list is complete — do NOT add, invent, or reference any "
        "variants not explicitly present in that list. "
        "Include sections for: classification, wild type, unknown variant features, similar "
        "variants (ONLY from the list below), likely behavior/expression based ONLY on "
        "similar known variants in the list, 3D structures, and research-only disclaimer.\n\n"
        f"{json.dumps(slim, indent=2)}"
    )
    try:
        async with httpx.AsyncClient(timeout=120) as client:
            response = await client.post(
                url,
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": model,
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0,
                },
            )
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"]
    except Exception as exc:
        print(f"[reporter] Groq failed: {exc}", flush=True)
        return None


async def _ollama_report(evidence: dict[str, Any]) -> str | None:
    """Fallback to local Ollama if available."""
    url = os.getenv("OLLAMA_URL", "http://localhost:11434/api/generate")
    model = os.getenv("OLLAMA_MODEL", "llama3")
    try:
        async with httpx.AsyncClient(timeout=120) as client:
            response = await client.post(
                url,
                json={
                    "model": model,
                    "prompt": (
                        "Generate a concise variant research report in markdown using the evidence:\n"
                        f"{json.dumps(evidence, indent=2)}"
                    ),
                    "stream": False,
                },
            )
            response.raise_for_status()
            return response.json().get("response")
    except Exception:
        return None


def _slim_evidence(evidence: dict[str, Any]) -> dict[str, Any]:
    """Return a slimmed copy of evidence safe to send to Groq.

    Raw PDB strings, full amino-acid sequences, and embedded ClinVar/PubMed
    evidence records push the payload over Groq's request size limit.
    We keep all semantic/descriptive data the LLM actually needs and drop
    the raw binary-ish blobs.
    """
    import copy

    slim = copy.deepcopy(evidence)

    # Strip raw sequences from the variant record.
    variant = slim.get("variant") or {}
    for key in ("wild_type_sequence", "mutant_sequence", "sequence"):
        if variant.get(key):
            variant[key] = f"<{key} omitted>"

    # Strip uniprot raw sequence (protein name/function/domains are kept).
    wt = slim.get("wild_type") or {}
    uniprot = wt.get("uniprot") or {}
    if uniprot.get("sequence"):
        uniprot["sequence"] = "<sequence omitted>"

    # Replace the entire structures block with a lightweight summary.
    raw_structures = slim.get("structures") or {}

    def _struct_summary(struct: dict[str, Any] | None) -> dict[str, Any]:
        if not isinstance(struct, dict):
            return {"available": False}
        viewer = struct.get("viewer") or {}
        return {
            "label": struct.get("label"),
            "source": struct.get("source"),
            "sequence_length": struct.get("sequence_length"),
            "available": viewer.get("available", bool(struct.get("pdb"))),
        }

    slim["structures"] = {
        "wild_type": _struct_summary(raw_structures.get("wild_type")),
        "unknown_variant": _struct_summary(raw_structures.get("unknown_variant")),
        "similar_variants": [
            {
                "name": (entry.get("variant") or {}).get("name"),
                "structure": _struct_summary(entry.get("structure")),
            }
            for entry in (raw_structures.get("similar_variants") or [])
        ],
    }

    return slim


def _fallback_markdown(evidence: dict[str, Any]) -> str:
    variant = evidence["variant"]
    summary = evidence["classification_summary"]
    unknown = evidence["unknown_variant"]
    wild_type = evidence["wild_type"]
    similar = evidence["similar_variants"]
    structures = evidence["structures"]
    warnings = evidence["warnings"]

    lines = [
        "# Variant Research Report",
        "",
        f"## Variant",
        f"- Input: {variant.get('input_text')}",
        f"- Parsed variant: {variant.get('display_name')}",
        f"- Gene: {variant.get('gene') or 'unknown'}",
        "",
        "## Benign / Pathogenic Evidence",
        f"- Overall interpretation: {summary['overall_interpretation']}",
        f"- AlphaMissense status: {summary.get('alpha_missense', {}).get('status')}",
        f"- ClinVar records found: {len(summary.get('clinvar') or [])}",
        f"- Population frequency: {summary.get('gnomad', {}).get('population_frequency')}",
        "",
        "## Wild Type",
        f"- Protein: {wild_type.get('protein') or 'unknown'}",
        f"- Sequence length: {wild_type.get('sequence_length') or 'unknown'}",
        f"- Description: {wild_type.get('description')}",
        "",
        "## Unknown Variant Features",
        f"- Description: {unknown.get('description')}",
        f"- Mutation features: {json.dumps(unknown.get('features', {}).get('mutation'), default=str)}",
        "",
        "## Similar Known Variants",
    ]
    if similar:
        for item in similar:
            lines.append(
                f"- {item.get('name')}: score {item.get('similarity_score')} "
                f"({'; '.join(item.get('similarity_reasons') or [])}). "
                f"{item.get('description')}"
            )
    else:
        lines.append("- No similar variants were found from the available evidence.")

    lines.extend(
        [
            "",
            "## Likely Behavior / Expression",
            _behavior_summary(similar),
            "",
            "## 3D Structures",
            f"- Wild type model available: {structures.get('wild_type', {}).get('viewer', {}).get('available')}",
            f"- Unknown variant model available: {structures.get('unknown_variant', {}).get('viewer', {}).get('available')}",
            f"- Similar variant models: {len(structures.get('similar_variants') or [])}",
            "",
            "## Warnings",
        ]
    )
    lines.extend([f"- {warning}" for warning in warnings] or ["- None"])
    lines.extend(
        [
            "",
            "Research support only. This is not medical advice, diagnosis, or treatment guidance.",
        ]
    )
    return "\n".join(lines)


def _overall_interpretation(alpha: dict[str, Any], clinvar_records: list[dict[str, Any]]) -> str:
    clinvar_labels = " ".join(
        (record.get("clinical_significance") or "").lower() for record in clinvar_records
    )
    pathogenic = any(
        term in clinvar_labels
        for term in ("pathogenic", "oncogenic", "likely pathogenic", "likely oncogenic")
    )
    benign = any(term in clinvar_labels for term in ("benign", "likely benign"))
    if pathogenic and not benign:
        return "Known ClinVar evidence includes pathogenic or oncogenic assertions."
    if benign and not pathogenic:
        return "Known ClinVar evidence includes benign assertions."
    if pathogenic and benign:
        return "Conflicting ClinVar evidence — both pathogenic/oncogenic and benign assertions present."
    predictions = alpha.get("predictions") or []
    if predictions:
        return "AlphaMissense predictions are available and should be reviewed with ClinVar and frequency evidence."
    return "Insufficient evidence for benign/pathogenic classification."


def _wild_type_description(annotations: dict[str, Any]) -> str:
    uniprot = annotations.get("uniprot") or {}
    functions = uniprot.get("function") or []
    if functions:
        return functions[0]
    return "Wild-type function was not available from the current evidence."


def _unknown_variant_description(variant: dict[str, Any], features: dict[str, Any]) -> str:
    mutation = variant.get("mutation") or {}
    feature_mutation = features.get("mutation") or {}
    pieces = [
        f"Substitution {mutation.get('protein_hgvs')}" if mutation.get("protein_hgvs") else None,
        f"at protein position {mutation.get('protein_position')}"
        if mutation.get("protein_position")
        else None,
        f"changes amino-acid class: {feature_mutation.get('class_change')}"
        if feature_mutation.get("class_change") is not None
        else None,
        f"hydropathy delta {feature_mutation.get('hydropathy_delta')}"
        if feature_mutation.get("hydropathy_delta") is not None
        else None,
    ]
    return "; ".join(piece for piece in pieces if piece) or "Variant features are incomplete."


def _behavior_summary(similar_variants: list[dict[str, Any]]) -> str:
    # Match any ClinVar-sourced variant regardless of exact source string variant.
    known = [
        item for item in similar_variants
        if "clinvar" in (item.get("source") or "").lower()
    ]
    if not known:
        return (
            "No known similar variants with ClinVar clinical assertions were available, so "
            "behavior or expression should not be inferred beyond the measured features."
        )
    labels = ", ".join(
        f"{item.get('name')} ({item.get('clinical_significance') or 'significance unknown'})"
        for item in known[:5]
    )
    return (
        f"Closest known ClinVar variants: {labels}. "
        "Interpret cautiously alongside the ranked similarity evidence."
    )
